import 'package:flutter/cupertino.dart';
import 'package:flutter_svg/flutter_svg.dart';

const SemiBold = FontWeight.w600;
const Medium = FontWeight.w500;

class Themes {
  final Colours colors;
  final TextStyles styles;
  final String suffix;

  Themes({required this.colors, required this.styles, required this.suffix});

  SvgPicture getSvgPicture(String name, {double? width, double? height, Key? key}) => SvgPicture.asset(
        'assets/$name$suffix.svg',
        width: width,
        height: height,
        key: key,
      );
}

class Colours {
  final Color neutral50,
      neutral100,
      neutral200,
      neutral300,
      neutral400,
      neutral500,
      neutral600,
      neutral700,
      neutral800,
      neutral900,
      primary50,
      primary100,
      primary200,
      primary300,
      primary400,
      primary500,
      primary600,
      primary700,
      primary800,
      primary900,
      success50,
      success100,
      success200,
      success300,
      success400,
      success500,
      success600,
      success700,
      success800,
      success900,
      warning50,
      warning100,
      warning200,
      warning300,
      warning400,
      warning500,
      warning600,
      warning700,
      warning800,
      warning900,
      destructive50,
      destructive100,
      destructive200,
      destructive300,
      destructive400,
      destructive500,
      destructive600,
      destructive700,
      destructive800,
      destructive900,
      background,
      white,
      black;

  Colours(
      {required this.neutral50,
      required this.neutral100,
      required this.neutral200,
      required this.neutral300,
      required this.neutral400,
      required this.neutral500,
      required this.neutral600,
      required this.neutral700,
      required this.neutral800,
      required this.neutral900,
      required this.primary50,
      required this.primary100,
      required this.primary200,
      required this.primary300,
      required this.primary400,
      required this.primary500,
      required this.primary600,
      required this.primary700,
      required this.primary800,
      required this.primary900,
      required this.success50,
      required this.success100,
      required this.success200,
      required this.success300,
      required this.success400,
      required this.success500,
      required this.success600,
      required this.success700,
      required this.success800,
      required this.success900,
      required this.warning50,
      required this.warning100,
      required this.warning200,
      required this.warning300,
      required this.warning400,
      required this.warning500,
      required this.warning600,
      required this.warning700,
      required this.warning800,
      required this.warning900,
      required this.destructive50,
      required this.destructive100,
      required this.destructive200,
      required this.destructive300,
      required this.destructive400,
      required this.destructive500,
      required this.destructive600,
      required this.destructive700,
      required this.destructive800,
      required this.destructive900,
      required this.background,
      required this.white,
      required this.black});
}

class TextStyles {
  final TextStyle extraBold36,
      extraBold32,
      extraBold28,
      extraBold24,
      extraBold20,
      extraBold18,
      bold36,
      bold32,
      bold28,
      bold24,
      bold20,
      bold18,
      semiBold18,
      semiBold16,
      semiBold14,
      semiBold12,
      medium18,
      medium16,
      medium14,
      medium12,
      regular18,
      regular16,
      regular14,
      regular12,
      light18,
      light16,
      light14,
      light12;

  TextStyles({
    required this.extraBold36,
    required this.extraBold32,
    required this.extraBold28,
    required this.extraBold24,
    required this.extraBold20,
    required this.extraBold18,
    required this.bold36,
    required this.bold32,
    required this.bold28,
    required this.bold24,
    required this.bold20,
    required this.bold18,
    required this.semiBold18,
    required this.semiBold16,
    required this.semiBold14,
    required this.semiBold12,
    required this.medium16,
    required this.medium18,
    required this.medium14,
    required this.medium12,
    required this.regular18,
    required this.regular16,
    required this.regular14,
    required this.regular12,
    required this.light18,
    required this.light16,
    required this.light14,
    required this.light12,
  });
}
